apiVersion: v1
kind: ConfigMap
metadata:
  name: mural-config
  labels:
    {{- include "mural.labels" . | nindent 4 }}
data:
  API_PORT: {{ .Values.api.port | quote }}
  API_UPSTREAM: "mural-api:{{ .Values.api.port }}"
