apiVersion: v1
kind: ConfigMap
metadata:
  name: mural-migrations
  labels:
    {{- include "mural.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
{{- range $path, $_ := .Files.Glob "files/migrations/*.sql" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
